/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function startListener(callback: (event: string) => void): void
export declare function getSelectionText(): string
export declare function getMousePos(): string
